let CSS = {
  arena: {
    width: 900,
    height: 600,
    background: "#000",
    position: "fixed",
    top: "50%",
    left: "50%",
    zIndex: "999",
    transform: "translate(-50%, -50%)",
    borderRadius: "15px",
    border: "1px solid #fff",
  },
  ball: {
    width: 15,
    height: 15,
    position: "absolute",
    top: 292.5,
    left: 442.5,
    borderRadius: 50,
    background: "#81C14B",
  },
  line: {
    width: 0,
    height: 600,
    borderLeft: "2px dashed #FFF",
    position: "absolute",
    top: 0,
    left: "50%",
  },
  stick: {
    width: 12,
    height: 85,
    position: "absolute",
    background: "#000",
    borderRadius: "15px",
    border: "1px solid pink",
  },
  stick1: {
    left: 0,
    top: 257.5,
  },
  stick2: {
    left: 888,
    top: 257.5,
  },
  scoreTable: {
    width: 30,
    height: 30,
    color: "#FFF",
    fontSize: 50,
    position: "absolute",
  },
  score1: {
    left: "30%",
    top: 10,
  },
  score2: {
    right: "30%",
    top: 10,
  },
  winner: {
    width: 450,
    height: 250,
    background: "#586F6B",
    position: "fixed",
    top: "50%",
    left: "50%",
    zIndex: "999",
    transform: "translate(-50%, -50%)",
    borderRadius: "15px",
  },
  winnerText: {
    textAlign: "center",
    color: "#000",
    fontSize: 40,
    padding: 50,
    fontFamily: "Arial",
  },
  winnerButton: {
    position: "absolute",
    textAlign: "center",
    backgroundColor: "#CFC0BD",
    bottom: 20,
    left: 150,
    fontSize: 18,
    fontFamily: "Arial",
    borderRadius: "15px",
    padding: "10px",
    cursor: "pointer",
  },
  menu: {
    width: 450,
    height: 150,
    backgroundColor: "#000",
    position: "fixed",
    top: "50%",
    left: "50%",
    zIndex: "999",
    transform: "translate(-50%, -50%)",
    borderRadius: "15px",
    border: "2px solid #CCC",
  },
  menuButton: {
    boxShadow: "0px 1px 0px 0px #1c1b18",
    backgroundColor: "#000",
    borderRadius: "15px",
    border: "2px solid #fff",
    display: "inline-block",
    cursor: "pointer",
    color: "#fff",
    fontFamily: "Arial",
    fontSize: "14px",
    fontWeight: "bold",
    padding: "12px 16px",
    textDecoration: "none",
    textShadow: "0px 1px 0px #ffffff",
    marginLeft: "15px",
    marginTop: "50px",
  },

  pointer: {
    position: "absolute",
    top: 292.5,
    left: 442.5,
    width: 15,
    height: 15,
    background: "#dc143c",
    border: "1px solid rgba(255,255,255, .1)",
    borderRadius: 60,
    pointerEvents: "none",
    boxSizing: "border-box",
  },
  pointer1: {
    transition: "0.01s",
    opacity: 0.5,
  },
  pointer2: {
    transition: "0.05s",
    opacity: 0.4,
    filter: "blur(0px)",
  },
  pointer3: {
    transition: "0.07s",
    opacity: 0.35,
    filter: "blur(1px)",
  },
  pointer4: {
    transition: "0.09s",
    opacity: 0.3,
    filter: "blur(2px)",
  },
  pointer5: {
    transition: "0.11s",
    opacity: 0.2,
    filter: "blur(3px)",
  },
  pointer6: {
    transition: "0.13s",
    opacity: 0.15,
    filter: "blur(4px)",
  },
}

let CONSTS = {
  gameSpeed: 20,
  score1: 0,
  score2: 0,
  stick1Speed: 0,
  stick2Speed: 0,
  ballTopSpeed: 0,
  ballLeftSpeed: 0,
  game_mode: "",
  winner_text_size: 0,
  ballCount: 1,
}
